# IMPORTANT: This file was generated by Cucumber 0.4.2
# Edit at your own peril - it's recommended to regenerate this file
# in the future when you upgrade to a newer version of Cucumber.

config.cache_classes = true # This must be true for Cucumber to operate correctly!

# Log error messages when you accidentally call methods on nil.
config.whiny_nils = true

# Show full error reports and disable caching
config.action_controller.consider_all_requests_local = true
config.action_controller.perform_caching             = false

# Disable request forgery protection in test environment
config.action_controller.allow_forgery_protection    = false

# Tell Action Mailer not to deliver emails to the real world.
# The :test delivery method accumulates sent emails in the
# ActionMailer::Base.deliveries array.
config.action_mailer.delivery_method = :test

unless File.directory?(File.join(Rails.root, 'vendor/plugins/cucumber'))
  config.gem 'cucumber',
    :lib     => false,
    :version => '>=0.4.2'
end

unless File.directory?(File.join(Rails.root, 'vendor/plugins/webrat'))
  config.gem 'webrat',
    :lib     => false,
    :version => '>=0.5.0'
end

config.gem 'fakeweb',
  :version => '>= 1.2.5'
config.gem 'factory_girl', 
  :source  => 'http://gemcutter.org',
  :version => '>= 1.2.3'

HOST = "localhost"
AUTHORIZE_NET_API_LOGIN_ID    = ''
AUTHORIZE_NET_TRANSACTION_KEY = ''
ActiveMerchant::Billing::Base.gateway_mode = :test

